import { DateTime } from "luxon";
import type { WebstoreItem } from "./PageTypes";

export const exampleItems: WebstoreItem[] = [
  // ── Characters – Melee ──────────────────────────────────────────
  {
    id: "c1",
    name: "Iron Knight",
    kind: "Character",
    combatType: "Melee",
    rarity: "Common",
    description: "A steadfast knight clad in iron armor.",
    price: 100,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c2",
    name: "Brawler",
    kind: "Character",
    combatType: "Melee",
    rarity: "Common",
    description: "Fights with bare fists and raw strength.",
    price: 80,
    owned: true,
    createdAt: DateTime.now(),
  },
  {
    id: "c3",
    name: "Shadow Rogue",
    kind: "Character",
    combatType: "Melee",
    rarity: "Uncommon",
    description: "Strikes from the shadows with dual daggers.",
    price: 250,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c4",
    name: "Berserker",
    kind: "Character",
    combatType: "Melee",
    rarity: "Uncommon",
    description: "Enters a frenzied rage, dealing massive damage.",
    price: 300,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c5",
    name: "Paladin",
    kind: "Character",
    combatType: "Melee",
    rarity: "Rare",
    description: "A holy warrior with both offense and healing.",
    price: 600,
    owned: true,
    createdAt: DateTime.now(),
  },
  {
    id: "c6",
    name: "Blademaster",
    kind: "Character",
    combatType: "Melee",
    rarity: "Rare",
    description: "Unparalleled swordsmanship and swift combos.",
    price: 650,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c7",
    name: "Death Knight",
    kind: "Character",
    combatType: "Melee",
    rarity: "Epic",
    description: "Wields cursed blades that drain life force.",
    price: 1200,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c8",
    name: "Titan",
    kind: "Character",
    combatType: "Melee",
    rarity: "Epic",
    description: "An enormous warrior with earth-shattering attacks.",
    price: 1500,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c9",
    name: "Void Slayer",
    kind: "Character",
    combatType: "Melee",
    rarity: "Legendary",
    description: "Cuts through dimensions with every swing.",
    price: 3000,
    owned: false,
    createdAt: DateTime.now(),
  },

  // ── Characters – Ranged ─────────────────────────────────────────
  {
    id: "c10",
    name: "Scout",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Common",
    description: "A nimble archer with keen eyesight.",
    price: 90,
    owned: true,
    createdAt: DateTime.now(),
  },
  {
    id: "c11",
    name: "Gunslinger",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Common",
    description: "Quick on the draw with twin pistols.",
    price: 100,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c12",
    name: "Fire Mage",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Uncommon",
    description: "Hurls fireballs and conjures flame walls.",
    price: 280,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c13",
    name: "Frost Archer",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Uncommon",
    description: "Arrows that freeze enemies on impact.",
    price: 300,
    owned: true,
    createdAt: DateTime.now(),
  },
  {
    id: "c14",
    name: "Storm Mage",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Rare",
    description: "Channels devastating lightning from afar.",
    price: 650,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c15",
    name: "Sniper",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Rare",
    description: "One shot, one kill from extreme distance.",
    price: 700,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c16",
    name: "Warlock",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Epic",
    description: "Dark sorcerer commanding forbidden spells.",
    price: 1300,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c17",
    name: "Dragon Sage",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Epic",
    description: "Summons dragon breath from ancient magic.",
    price: 1500,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "c18",
    name: "Celestial Archer",
    kind: "Character",
    combatType: "Ranged",
    rarity: "Legendary",
    description: "Arrows blessed by starlight never miss.",
    price: 3500,
    owned: false,
    createdAt: DateTime.now(),
  },

  // ── Skins ───────────────────────────────────────────────────────
  {
    id: "s1",
    name: "Forest Camo",
    kind: "Skin",
    rarity: "Common",
    description: "A woodland camouflage pattern.",
    price: 50,
    owned: true,
    createdAt: DateTime.now(),
  },
  {
    id: "s2",
    name: "Desert Dust",
    kind: "Skin",
    rarity: "Common",
    description: "Sandy tones for arid environments.",
    price: 50,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s3",
    name: "Ocean Blue",
    kind: "Skin",
    rarity: "Common",
    description: "Deep blue colors inspired by the sea.",
    price: 60,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s4",
    name: "Crimson Fury",
    kind: "Skin",
    rarity: "Uncommon",
    description: "Blazing red with flame accents.",
    price: 150,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s5",
    name: "Arctic Frost",
    kind: "Skin",
    rarity: "Uncommon",
    description: "Icy white with frozen crystal effects.",
    price: 150,
    owned: true,
    createdAt: DateTime.now(),
  },
  {
    id: "s6",
    name: "Neon Pulse",
    kind: "Skin",
    rarity: "Uncommon",
    description: "Glowing neon lines over dark material.",
    price: 175,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s7",
    name: "Shadow Veil",
    kind: "Skin",
    rarity: "Rare",
    description: "Dark, ethereal smoke that trails behind.",
    price: 400,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s8",
    name: "Golden Emperor",
    kind: "Skin",
    rarity: "Rare",
    description: "Ornate golden armor with royal engravings.",
    price: 450,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s9",
    name: "Crystal Guardian",
    kind: "Skin",
    rarity: "Rare",
    description: "Translucent crystal plating with prismatic shine.",
    price: 500,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s10",
    name: "Infernal Lord",
    kind: "Skin",
    rarity: "Epic",
    description: "Molten lava cracks across obsidian armor.",
    price: 900,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s11",
    name: "Void Walker",
    kind: "Skin",
    rarity: "Epic",
    description: "A shifting void texture from another dimension.",
    price: 950,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s12",
    name: "Celestial Dawn",
    kind: "Skin",
    rarity: "Epic",
    description: "Heavenly glow with golden particle effects.",
    price: 1000,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s13",
    name: "Galactic Overlord",
    kind: "Skin",
    rarity: "Legendary",
    description: "A cosmic skin with swirling galaxies.",
    price: 2500,
    owned: false,
    createdAt: DateTime.now(),
  },
  {
    id: "s14",
    name: "Primordial Chaos",
    kind: "Skin",
    rarity: "Legendary",
    description: "Reality bends around this ancient skin.",
    price: 3000,
    owned: false,
    createdAt: DateTime.now(),
  },
];
