import { DateTime } from "luxon";
import type { Release } from "./PageTypes";

export const exampleReleases: Release[] = [
  {
    id: "1",
    version: "1.0.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  { id: "2", version: "1.0.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "3",
    version: "1.0.2",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "4",
    version: "1.1.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  { id: "5", version: "1.1.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "6",
    version: "1.1.2",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "7", version: "1.2.0", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "8",
    version: "1.2.1",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "9",
    version: "1.3.0",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "10", version: "1.3.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "11",
    version: "2.0.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  { id: "12", version: "2.0.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "13",
    version: "2.0.2",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "14",
    version: "2.0.3",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  { id: "15", version: "2.1.0", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "16",
    version: "2.1.1",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "17",
    version: "2.1.2",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "18",
    version: "2.2.0",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "19", version: "2.2.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "20",
    version: "2.3.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "21",
    version: "3.0.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "22",
    version: "3.0.1",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "23", version: "3.0.2", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "24",
    version: "3.1.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  { id: "25", version: "3.1.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "26",
    version: "3.1.2",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "27", version: "3.2.0", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "28",
    version: "3.2.1",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "29",
    version: "3.3.0",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "30",
    version: "3.3.1",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "31",
    version: "4.0.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  { id: "32", version: "4.0.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "33",
    version: "4.0.2",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "34",
    version: "4.1.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "35",
    version: "4.1.1",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "36", version: "4.2.0", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "37",
    version: "4.2.1",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "38",
    version: "4.2.2",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "39", version: "4.3.0", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "40",
    version: "4.3.1",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "41",
    version: "5.0.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "42",
    version: "5.0.1",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "43", version: "5.1.0", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "44",
    version: "5.1.1",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "45",
    version: "5.2.0",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "46", version: "5.2.1", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "47",
    version: "6.0.0",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
  {
    id: "48",
    version: "6.0.1",
    supports: ["Android"],
    createdAt: DateTime.now(),
  },
  { id: "49", version: "6.1.0", supports: ["iOS"], createdAt: DateTime.now() },
  {
    id: "50",
    version: "6.1.1",
    supports: ["iOS", "Android"],
    createdAt: DateTime.now(),
  },
];
