import { DateTime } from "luxon";
import type { Item } from "./PageTypes";

export const exampleItems: Item[] = [
  {
    id: "1",
    name: "Wooden Sword",
    category: "Weapons",
    rarity: "Common",
    description: "A basic wooden training sword.",
    price: 10,
    createdAt: DateTime.now(),
  },
  {
    id: "2",
    name: "Iron Shield",
    category: "Armor",
    rarity: "Common",
    description: "A sturdy iron shield for beginners.",
    price: 25,
    createdAt: DateTime.now(),
  },
  {
    id: "3",
    name: "Health Potion",
    category: "Consumables",
    rarity: "Common",
    description: "Restores a small amount of health.",
    price: 5,
    createdAt: DateTime.now(),
  },
  {
    id: "4",
    name: "Leather Boots",
    category: "Armor",
    rarity: "Common",
    description: "Simple leather boots for light travel.",
    price: 15,
    createdAt: DateTime.now(),
  },
  {
    id: "5",
    name: "Torch",
    category: "Utilities",
    rarity: "Common",
    description: "Provides light in dark areas.",
    price: 3,
    createdAt: DateTime.now(),
  },
  {
    id: "6",
    name: "Steel Dagger",
    category: "Weapons",
    rarity: "Uncommon",
    description: "A sharp steel dagger for quick strikes.",
    price: 45,
    createdAt: DateTime.now(),
  },
  {
    id: "7",
    name: "Chainmail Vest",
    category: "Armor",
    rarity: "Uncommon",
    description: "Interlocking steel rings offer solid protection.",
    price: 80,
    createdAt: DateTime.now(),
  },
  {
    id: "8",
    name: "Mana Elixir",
    category: "Consumables",
    rarity: "Uncommon",
    description: "Restores a moderate amount of mana.",
    price: 30,
    createdAt: DateTime.now(),
  },
  {
    id: "9",
    name: "Grappling Hook",
    category: "Utilities",
    rarity: "Uncommon",
    description: "Reach higher platforms with ease.",
    price: 50,
    createdAt: DateTime.now(),
  },
  {
    id: "10",
    name: "Hunting Bow",
    category: "Weapons",
    rarity: "Uncommon",
    description: "A reliable bow for ranged combat.",
    price: 60,
    createdAt: DateTime.now(),
  },
  {
    id: "11",
    name: "Flame Staff",
    category: "Weapons",
    rarity: "Rare",
    description: "Channels fire magic into devastating blasts.",
    price: 250,
    createdAt: DateTime.now(),
  },
  {
    id: "12",
    name: "Enchanted Helmet",
    category: "Armor",
    rarity: "Rare",
    description: "A helmet imbued with protective runes.",
    price: 200,
    createdAt: DateTime.now(),
  },
  {
    id: "13",
    name: "Revival Salve",
    category: "Consumables",
    rarity: "Rare",
    description: "Instantly revives a fallen ally.",
    price: 150,
    createdAt: DateTime.now(),
  },
  {
    id: "14",
    name: "Teleport Stone",
    category: "Utilities",
    rarity: "Rare",
    description: "Warps you to a previously visited location.",
    price: 175,
    createdAt: DateTime.now(),
  },
  {
    id: "15",
    name: "Shadow Cloak",
    category: "Armor",
    rarity: "Rare",
    description: "Grants brief invisibility when standing still.",
    price: 220,
    createdAt: DateTime.now(),
  },
  {
    id: "16",
    name: "Frost Axe",
    category: "Weapons",
    rarity: "Rare",
    description: "Each swing chills enemies to the bone.",
    price: 275,
    createdAt: DateTime.now(),
  },
  {
    id: "17",
    name: "Potion of Speed",
    category: "Consumables",
    rarity: "Uncommon",
    description: "Temporarily boosts movement speed.",
    price: 35,
    createdAt: DateTime.now(),
  },
  {
    id: "18",
    name: "Iron Gauntlets",
    category: "Armor",
    rarity: "Common",
    description: "Heavy-duty gauntlets for melee fighters.",
    price: 20,
    createdAt: DateTime.now(),
  },
  {
    id: "19",
    name: "Smoke Bomb",
    category: "Utilities",
    rarity: "Uncommon",
    description: "Creates a cloud of smoke for quick escapes.",
    price: 40,
    createdAt: DateTime.now(),
  },
  {
    id: "20",
    name: "Crystal Wand",
    category: "Weapons",
    rarity: "Rare",
    description: "Amplifies magical energy for spellcasters.",
    price: 300,
    createdAt: DateTime.now(),
  },
  {
    id: "21",
    name: "Dragonscale Armor",
    category: "Armor",
    rarity: "Epic",
    description: "Forged from the scales of a fallen dragon.",
    price: 750,
    createdAt: DateTime.now(),
  },
  {
    id: "22",
    name: "Thunderblade",
    category: "Weapons",
    rarity: "Epic",
    description: "Crackles with lightning on every strike.",
    price: 800,
    createdAt: DateTime.now(),
  },
  {
    id: "23",
    name: "Phoenix Feather",
    category: "Consumables",
    rarity: "Epic",
    description: "Auto-revives the holder upon defeat.",
    price: 500,
    createdAt: DateTime.now(),
  },
  {
    id: "24",
    name: "Void Amulet",
    category: "Accessories",
    rarity: "Epic",
    description: "Absorbs incoming dark magic damage.",
    price: 650,
    createdAt: DateTime.now(),
  },
  {
    id: "25",
    name: "Titan Gauntlets",
    category: "Armor",
    rarity: "Epic",
    description: "Grants immense strength to the wearer.",
    price: 700,
    createdAt: DateTime.now(),
  },
  {
    id: "26",
    name: "Celestial Bow",
    category: "Weapons",
    rarity: "Legendary",
    description: "Arrows guided by starlight never miss.",
    price: 2000,
    createdAt: DateTime.now(),
  },
  {
    id: "27",
    name: "Aegis of Eternity",
    category: "Armor",
    rarity: "Legendary",
    description: "An indestructible shield from an ancient era.",
    price: 2500,
    createdAt: DateTime.now(),
  },
  {
    id: "28",
    name: "Elixir of Immortality",
    category: "Consumables",
    rarity: "Legendary",
    description: "Grants invincibility for a short time.",
    price: 1500,
    createdAt: DateTime.now(),
  },
  {
    id: "29",
    name: "World Compass",
    category: "Utilities",
    rarity: "Legendary",
    description: "Reveals the entire map and all secrets.",
    price: 1800,
    createdAt: DateTime.now(),
  },
  {
    id: "30",
    name: "Soulreaper Scythe",
    category: "Weapons",
    rarity: "Legendary",
    description: "Harvests the life force of defeated foes.",
    price: 3000,
    createdAt: DateTime.now(),
  },
  {
    id: "31",
    name: "Bandage Roll",
    category: "Consumables",
    rarity: "Common",
    description: "Slowly heals wounds over time.",
    price: 8,
    createdAt: DateTime.now(),
  },
  {
    id: "32",
    name: "Copper Ring",
    category: "Accessories",
    rarity: "Common",
    description: "A simple ring with no special powers.",
    price: 12,
    createdAt: DateTime.now(),
  },
  {
    id: "33",
    name: "Rope Coil",
    category: "Utilities",
    rarity: "Common",
    description: "Useful for climbing and tying things down.",
    price: 7,
    createdAt: DateTime.now(),
  },
  {
    id: "34",
    name: "Silver Rapier",
    category: "Weapons",
    rarity: "Uncommon",
    description: "A lightweight blade favored by duelists.",
    price: 55,
    createdAt: DateTime.now(),
  },
  {
    id: "35",
    name: "Emerald Pendant",
    category: "Accessories",
    rarity: "Uncommon",
    description: "Slightly boosts natural health regeneration.",
    price: 65,
    createdAt: DateTime.now(),
  },
  {
    id: "36",
    name: "Reinforced Greaves",
    category: "Armor",
    rarity: "Uncommon",
    description: "Leg armor that reduces knockback effects.",
    price: 70,
    createdAt: DateTime.now(),
  },
  {
    id: "37",
    name: "Explosive Barrel",
    category: "Utilities",
    rarity: "Rare",
    description: "Place it down and watch the fireworks.",
    price: 120,
    createdAt: DateTime.now(),
  },
  {
    id: "38",
    name: "Venomfang Blade",
    category: "Weapons",
    rarity: "Rare",
    description: "Coated in toxin that poisons on contact.",
    price: 260,
    createdAt: DateTime.now(),
  },
  {
    id: "39",
    name: "Mirror Shield",
    category: "Armor",
    rarity: "Rare",
    description: "Reflects a portion of incoming magic.",
    price: 240,
    createdAt: DateTime.now(),
  },
  {
    id: "40",
    name: "Lucky Charm",
    category: "Accessories",
    rarity: "Rare",
    description: "Increases drop rates from defeated enemies.",
    price: 180,
    createdAt: DateTime.now(),
  },
  {
    id: "41",
    name: "Abyssal Trident",
    category: "Weapons",
    rarity: "Epic",
    description: "A weapon forged in the deepest ocean trench.",
    price: 850,
    createdAt: DateTime.now(),
  },
  {
    id: "42",
    name: "Stormweaver Robe",
    category: "Armor",
    rarity: "Epic",
    description: "Channels storm energy to reduce cooldowns.",
    price: 720,
    createdAt: DateTime.now(),
  },
  {
    id: "43",
    name: "Greater Heal Potion",
    category: "Consumables",
    rarity: "Epic",
    description: "Fully restores health in an instant.",
    price: 400,
    createdAt: DateTime.now(),
  },
  {
    id: "44",
    name: "Dimensional Satchel",
    category: "Utilities",
    rarity: "Epic",
    description: "Holds far more than its size suggests.",
    price: 600,
    createdAt: DateTime.now(),
  },
  {
    id: "45",
    name: "Ring of the Phoenix",
    category: "Accessories",
    rarity: "Epic",
    description: "Resurrects the wearer once per battle.",
    price: 900,
    createdAt: DateTime.now(),
  },
  {
    id: "46",
    name: "Excalibur",
    category: "Weapons",
    rarity: "Legendary",
    description: "The legendary sword of kings.",
    price: 5000,
    createdAt: DateTime.now(),
  },
  {
    id: "47",
    name: "Crown of the Cosmos",
    category: "Armor",
    rarity: "Legendary",
    description: "A crown that grants cosmic awareness.",
    price: 4500,
    createdAt: DateTime.now(),
  },
  {
    id: "48",
    name: "Ambrosia",
    category: "Consumables",
    rarity: "Legendary",
    description: "Food of the gods — permanently boosts a stat.",
    price: 3500,
    createdAt: DateTime.now(),
  },
  {
    id: "49",
    name: "Chrono Hourglass",
    category: "Utilities",
    rarity: "Legendary",
    description: "Rewinds time by a few seconds in combat.",
    price: 4000,
    createdAt: DateTime.now(),
  },
  {
    id: "50",
    name: "Heart of the World",
    category: "Accessories",
    rarity: "Legendary",
    description: "An artifact said to contain infinite power.",
    price: 9999,
    createdAt: DateTime.now(),
  },
];
