services:
  - type: web
    name: smaash-web
    runtime: go
    branch: test
    rootDir: .
    region: frankfurt
    plan: starter
    autoDeployTrigger: commit
    buildCommand: cd client && npm ci && npm run build && cd .. && mkdir -p build && go build -o ./build/main ./cmd/api/main.go && go build -o ./build/seeder ./cmd/seeder/main.go
    startCommand: ./build/seeder && ./build/main
    disk:
      name: smaash-data-disk
      mountPath: /var/data
      sizeGB: 5
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_URL
        value: /var/data/test.db
      - key: UPLOAD_DIR
        value: /var/data/pfps
      - key: SEED_DATA_URI
        value: ./internal/seeder/test_source
  - type: web
    name: smaash-web-backend
    runtime: go
    branch: backend
    rootDir: .
    region: frankfurt
    plan: free
    autoDeployTrigger: commit
    buildCommand: cd client && npm ci && npm run build && cd .. && mkdir -p build && go build -o ./build/main ./cmd/api/main.go && go build -o ./build/seeder ./cmd/seeder/main.go
    startCommand: ./build/seeder && ./build/main
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_URL
        value: test.db
      - key: UPLOAD_DIR
        value: ./uploads/pfps
      - key: SEED_DATA_URI
        value: ./internal/seeder/test_source
