services:
  - type: web
    name: smaash-web
    runtime: go
    region: frankfurt
    plan: free
    autoDeployTrigger: commit
    buildCommand: cd client && npm ci && npm run build && cd .. && go build -o build/main cmd/api/main.go && go build -o build/seeder cmd/seeder/main.go
    preDeployCommand: ./build/seeder
    startCommand: ./build/main
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_URL
        value: test.db
      - key: UPLOAD_DIR
        value: ./uploads/pfps
      - key: SEED_DATA_URI
        value: ./internal/seeder/test_source
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_ROLE_ID
        value: "1"
