// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire_gen

import (
	"smaash-web/internal/controllers"
	"smaash-web/internal/database"
	"smaash-web/internal/repository"
	"smaash-web/internal/server"
	"smaash-web/internal/services"
)

// Injectors from wire.go:

func InitializeServer() *server.Server {
	db := database.NewGormDBConn()
	userRepository := repository.NewGormUserRepo(db)
	playerProfileRepository := repository.NewGormPlayerProfileRepo(db)
	userController := controllers.NewUserController(userRepository, playerProfileRepository)
	authentication := services.NewAuthenticationService(userRepository)
	authnController := controllers.NewAuthnController(authentication)
	gameAuthController := controllers.NewGameAuthController(userRepository)
	levelRepository := repository.NewGormLevelRepo(db)
	levelsController := controllers.NewLevelsController(levelRepository)
	playerProfileController := controllers.NewPlayerProfileController(playerProfileRepository)
	roleRepository := repository.NewGormRoleRepo(db)
	rolesController := controllers.NewRolesController(roleRepository)
	serverServer := server.NewServer(userController, authnController, gameAuthController, levelsController, playerProfileController, rolesController)
	return serverServer
}
