// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"smaash-web/internal/controllers"
	"smaash-web/internal/repository"
	"smaash-web/internal/server"
	"smaash-web/internal/services"
)

// Injectors from wire.go:

func InitializeServer() *server.Server {
	userRepository := repository.NewGormUserRepo()
	playerProfileRepository := repository.NewGormPlayerProfileRepo()
	userController := controllers.NewUserController(userRepository, playerProfileRepository)
	authentication := services.NewAuthenticationService(userRepository)
	authnController := controllers.NewAuthnController(authentication)
	gameAuthController := controllers.NewGameAuthController(userRepository, playerProfileRepository)
	levelRepository := repository.NewGormLevelRepo()
	levelsController := controllers.NewLevelsController(levelRepository)
	playerProfileController := controllers.NewPlayerProfileController(playerProfileRepository)
	serverServer := server.NewServer(userController, authnController, gameAuthController, levelsController, playerProfileController)
	return serverServer
}
